---
title: "Processing"
author: "John Brandt"
date: "9/15/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
age_gender_race <- read.csv("results/output-wiki-pred-race.csv")
race <- read.csv("results/results-image-race.csv")
```

```{r}
colnames(race) <- c("race-image", "name")
race$name <- gsub("[.]{1,}/img/", "", race$name)
race$name <- gsub("[.][A-z]{1,}", "", race$name)
race$name <- as.numeric(race$name)

library(tidyverse)
joined <- left_join(age_gender_race, race)
```

```{r}
joined$race <- as.character(joined$race)
joined$race[joined$race == "GreaterEuropean,WestEuropean,Hispanic"] <- "Latino"
joined$race[joined$race %in% c("Asian,GreaterEastAsian,Japanese",
            "Asian,GreaterEastAsian,EastAsian")] <- "Asian"

joined$race[joined$race %in% c("GreaterEuropean,WestEuropean,Germanic",
                               "GreaterEuropean,WestEuropean,Italian",
                               "GreaterEuropean,WestEuropean,French",
                               "GreaterEuropean,British",
                               "GreaterEuropean,WestEuropean,Nordic",
                               "GreaterEuropean,Jewish",
                               "GreaterEuropean,EastEuropean"
                               )] <- "Caucasian"
```


```{r}
joined$`race-image`[is.na(joined$age)] <- NA
joined$`race-image`[joined$`race-image` == 2] <- "Caucasian"
joined$`race-image`[joined$`race-image` == 4] <- "Latino" 
joined$`race-image`[joined$`race-image` == 3] <- "Asian"
joined$`race-image`[joined$`race-image` == 0] <- "African"

```

```{r}
table(joined$`race-image`, joined$race)
```

```{r}
joined$race[joined$X__name == "nan nan"] <- NA
joined$race[grepl("^nan\\s+", joined$X__name)] <- NA
joined$race[grepl("^[A-z]{1}\\s+[A-z]{1}$", joined$X__name)] <- NA
```

## Accuracy - Race -- name

```{r}
unique(joined$X__name[joined$race=="Latino"])[sample(seq(1,length(unique(joined$X__name[joined$race=="Latino"])), 250))]
```

```{r}
unique(joined$X__name[joined$race=="Asian"])[sample(seq(1,length(unique(joined$X__name[joined$race=="Asian"])), 200))]
```


```{r}
unique(joined$X__name[joined$race=="Caucasian"])[sample(seq(1,length(unique(joined$X__name[joined$race=="Caucasian"])), 500))]
```

```{r}
unique(joined$X__name[joined$race=="GreaterAfrican,Africans"])[sample(seq(1,length(unique(joined$X__name[joined$race=="GreaterAfrican,Africans"])), 200))]
```

## Accuracy - Gender -- overall (name)

```{r}
unique(joined$first.name[joined$pred_gender == "female"])[sample(seq(1,length(unique(joined$first.name[joined$pred_gender == "female"])), 200))]
```

```{r}
unique(joined$first.name[joined$pred_gender == "male"])[sample(seq(1,length(unique(joined$first.name[joined$pred_gender == "male"])), 200))]
```

## Plot

```{r}
figdata <- joined %>%
  dplyr::group_by(age, pred_gender, race) %>%
  dplyr::summarise(n=n())%>%
  as.data.frame()

figdata$n <- as.numeric(figdata$n)
figdata <- figdata[!is.na(figdata$race),]

ggplot(data=figdata, aes(x=age, y=n, fill=pred_gender))+
  geom_col(data=figdata[figdata$pred_gender=="female",], width=1)+
  geom_col(data=figdata[figdata$pred_gender=="male",], aes(y=n*-1), width=1)+
  coord_flip()+
  theme_minimal()+
  scale_x_continuous(breaks=seq(10,70,10))+
  theme(panel.grid.minor.x=element_blank(),
        panel.grid.major.x=element_blank())+
  facet_wrap(.~race)
```


